# Deploy Unity to Itch (GitLab)
# Author:   AndrewMJordan
# Version:  0.3.0

variables:
  PROJECT_LOCATION: $CI_PROJECT_DIR/$PROJECT_ROOT
  BUILD_LOCATION: $CI_PROJECT_DIR/Builds/$BUILD_PLATFORM

.deploy-script:
  variables:
    GIT_DEPTH: 1
    GIT_CLEAN_FLAGS: -fd
  tags:
    - unity
    - windows
  script:
    - |
      dotnet new tool-manifest
      dotnet tool install Gooball
    - |
      $revision = git rev-parse --short HEAD
      echo "Building revision $revision for $BUILD_PLATFORM..."
      dotnet goo project build "$PROJECT_LOCATION" -- `
        -logfile log.txt `
        -buildTarget "$BUILD_PLATFORM" `
        -executeMethod Andtech.BuildUtility.Builder.Build `
        -revision "$revision" `
        -output "$BUILD_LOCATION"
      cat log.txt
    - |
      Invoke-RestMethod -Uri https://broth.itch.ovh/butler/windows-amd64/LATEST/archive/default -Outfile "butler.zip"
      Expand-Archive -Path butler.zip -Force -DestinationPath .
    - |
      $channel = $ITCH_CHANNEL
      if ($CI_COMMIT_BRANCH -eq "develop") {
        $channel = "$channel-head"
      }
      $itchTarget = "${ITCH_USER}/${ITCH_GAME}:${channel}"
      echo "Publishing $buildLocation to $itchTarget..."
      ./butler.exe push "$BUILD_LOCATION" "$itchTarget"

stages:
  - deploy

.win:deploy:
  stage: deploy
  extends: .deploy-script
  variables:
    BUILD_PLATFORM: "StandaloneWindows64"
    ITCH_CHANNEL: "win"
.osx:deploy:
  stage: deploy
  extends: .deploy-script
  variables:
    BUILD_PLATFORM: "StandaloneOSX"
    ITCH_CHANNEL: "osx"
.web:deploy:
  stage: deploy
  extends: .deploy-script
  variables:
    BUILD_PLATFORM: "WebGL"
    ITCH_CHANNEL: "html"
