# Deploy Unity to Itch (GitLab)
# Author:   AndrewMJordan
# Version:  0.2.1

variables:
  GIT_DEPTH: 1
  GIT_CLEAN_FLAGS: -fd

.strategy:
  parallel:
    matrix:
      - BUILD_PLATFORM: StandaloneWindows64
        ITCH_CHANNEL: win
      - BUILD_PLATFORM: StandaloneOSX
        ITCH_CHANNEL: osx
#      - BUILD_PLATFORM: WebGL
#        ITCH_CHANNEL: html

main:
  tags:
    - unity
  stage: deploy
  extends: .strategy
  script:
    - |
      # Helper locals
      $projectLocation = "$CI_PROJECT_DIR/$PROJECT_ROOT"
      $buildLocation = [System.IO.Path]::GetFullPath("$projectLocation/Builds/$BUILD_PLATFORM")
      
      # Install tools
      dotnet new tool-manifest
      dotnet tool install Gooball
      Invoke-RestMethod -Uri https://broth.itch.ovh/butler/windows-amd64/LATEST/archive/default -Outfile "butler.zip"
      Expand-Archive -Path butler.zip -Force -DestinationPath .

      # Build project
      $revision = git rev-parse --short HEAD
      echo "Building revision $revision for $BUILD_PLATFORM..."
      dotnet goo project build "$projectLocation" -- `
        -logfile log.txt `
        -buildTarget "$BUILD_PLATFORM" `
        -executeMethod Andtech.BuildUtility.Builder.Build `
        -revision "$revision" `
        -output "buildLocation"
      cat log.txt

      # Compute channel string
      $channel = $ITCH_CHANNEL
      if ( ![string]::IsNullOrWhiteSpace("$ITCH_SUFFIX") ) {
        $channel = "$channel-$ITCH_SUFFIX"
      }
      if ($CI_COMMIT_BRANCH -eq "develop") {
        $channel = "$channel-head"
      }

      # Publish
      $itchTarget = "${ITCH_USER}/${ITCH_GAME}:${channel}"
      echo "Publishing $buildLocation to $itchTarget..."
      ./butler.exe push "$buildLocation" "$itchTarget"
