name: $(BuildID)

trigger:
  - master
pr: none

stages:
- stage: build
  displayName: Build Stage
  jobs:
  - job:
    displayName: Build Project Job
    steps:
    - bash: |
        dotnet tool install --global Gooball || dotnet tool update --global Gooball
      displayName: 'Install Unity CLI'
    - powershell: |
        cd "$(Build.SourcesDirectory)"

        goo project build "$(Custom.ProjectRoot)" -- -executeMethod BuildUtility.Build
      displayName: 'Build project'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.SourcesDirectory)/$(Custom.ProjectRoot)/Builds'
        artifact: 'drop'
        publishLocation: 'pipeline'
      displayName: 'Publish build artifact'
- stage: deployment
  displayName: Deployment Stage
  pool:
    vmImage: ubuntu-latest
  jobs:
  - job:
    displayName: Deploy Build to Dropbox
    steps:
    - checkout: none
    - download: current
      artifact: drop
      displayName: 'Download build artifact'
    - task: ArchiveFiles@2
      displayName: 'Compress build'
      inputs:
        rootFolderOrFile: '$(Pipeline.Workspace)/drop'
        includeRootFolder: false
        archiveFile: '$(Agent.TempDirectory)/build.zip'
    - bash: |
        artifact="$(Agent.TempDirectory)/build.zip"
        remotePath="/$(Build.Repository.Name)/$(Build.BuildNumber).zip"
        
        curl -v -X POST https://content.dropboxapi.com/2/files/upload \
          --header "Authorization: Bearer $(Custom.AccessToken.Dropbox)" \
          --header "Dropbox-API-Arg: {\"path\": \"${remotePath}\"}" \
          --header "Content-Type: application/octet-stream" \
          --data-binary @"${artifact}"
      displayName: 'Upload to Dropbox'
